---
- name: Register OpenTofu APT repository
  ansible.builtin.deb822_repository:
    name: opentofu
    types: deb
    uris: https://packages.opentofu.org/opentofu/tofu/any/
    suites: any
    components: main
    signed_by: https://get.opentofu.org/opentofu.gpg
    state: present

- name: Install OpenTofu
  ansible.builtin.apt:
    name: tofu
    state: present
    update_cache: true
