---
- name: Установка Docker
  hosts: all
  become: true

  tasks:
    - name: Удаление пакета docker, если он был установлен ранее
      ansible.builtin.apt:
        name: docker
        state: absent

    - name: Удаление пакета docker-engine, если он был установлен ранее
      ansible.builtin.apt:
        name: docker-engine
        state: absent

    - name: Удаление пакета docker.io, если он был установлен ранее
      ansible.builtin.apt:
        name: docker.io
        state: absent

    - name: Удаление пакета containerd, если он был установлен ранее
      ansible.builtin.apt:
        name: containerd
        state: absent

    - name: Удаление пакета runc, если он был установлен ранее
      ansible.builtin.apt:
        name: containerd
        state: absent

    - name: Установка ключа GPG
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian.gpg
        dest: /etc/apt/trusted.gpg.d/docker.gpg
        state: present

    - name: Подключение репозитория
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux debian bullseye stable
        state: present
        filename: /etc/apt/sources.list.d/docker.list
        update_cache: true

    - name: Установка пакетов Docker
      ansible.builtin.apt:
        pkg:
          docker-ce
          docker-ce-cli
          containerd.io
          docker-buildx-plugin
          docker-compose-plugin
