---
- name: Установка GNU EMACS и его расширений
  hosts: all
  become: true

  tasks:
    - name: Подключение стандартных репозиториев
      ansible.builtin.apt_repository:
        repo: deb http://ftp.ru.debian.org/debian/ bullseye main contrib non-free
        state: present
        filename: /etc/apt/sources.list
        update_cache: false

    - name: Подключение репозиториев с обновлениями ОС
      ansible.builtin.apt_repository:
        repo: deb http://ftp.ru.debian.org/debian/ bullseye-updates main contrib non-free
        state: present
        filename: /etc/apt/sources.list
        update_cache: false

    - name: Подключение репозиториев с обновлениями безопасности
      ansible.builtin.apt_repository:
        repo: deb http://security.debian.org/debian-security bullseye-security main contrib non-free
        state: present
        filename: /etc/apt/sources.list
        update_cache: false

    - name: Обновление списка пакетов
      ansible.builtin.apt:
        update_cache: true

    - name: Удаление EMACS Nox, если он установлен
      ansible.builtin.apt:
        name: emacs-nox
        state: absent

    - name: Установка пакетов GNU EMACS
      ansible.builtin.apt:
        pkg:
          - emacs
          - emacs-goodies-el
