---
- name: Установка клиента Mattermost
  hosts: all
  become: true

  tasks:
    - name: Установка ключа GPG
      ansible.builtin.apt_key:
        url: https://deb.packages.mattermost.com/pubkey.gpg
        keyring: /etc/apt/trusted.gpg.d/mattermost.gpg
        state: present

    - name: Подключение репозитория
      ansible.builtin.apt_repository:
        repo: deb https://deb.packages.mattermost.com stable main
        state: present
        filename: mattermost # /etc/apt/sources.list.d/mattermost.list
        update_cache: true  # apt update

    - name: Установка пакета Mattermost Desktop
      ansible.builtin.apt:
        name: mattermost-desktop
        state: present
