---
- name: Установка NodeJS
  hosts: all
  become: true

  tasks:
    - name: Установка ключа GPG
      ansible.builtin.apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        keyring: /etc/apt/trusted.gpg.d/nodesource.gpg
        state: present

    - name: Подключение репозитория
      ansible.builtin.apt_repository:
        repo: deb https://deb.nodesource.com/node_18.x bullseye main
        state: present
        filename: nodejs # /etc/apt/sources.list.d/nodesource.list
        update_cache: true  # apt update

    - name: Установка пакета NodeJS
      ansible.builtin.apt:
        name: nodejs
        state: present
