---
# На основе статьи Debian Wiki: https://wiki.debian.org/ru/KVM
- name: Установка QEMU-KVM
  hosts: all
  become: true

  tasks:

    - name: Установка пакетов QEMU-KVM
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - qemu-kvm
          - libvirt-clients
          - libvirt-daemon-system
          - virt-manager

    - name: Включить автозапуск сети `default`
      ansible.builtin.command: virsh net-autostart --network default
      become: true
