---
- name: Установка Ruby on Rails
  hosts: all
  become: true

  tasks:
    - name: Установка пакетов, необходимых для сборки нативных расширений
      ansible.builtin.apt:
        update_cache: yes
        pkg:
        - libedit-dev
        - libffi-dev
        - libssl-dev
        - libyaml-dev
        - ruby
        - ruby-dev
