---
- name: Установка HashiCorp Terraform
  hosts: all
  become: true

  tasks:
    - name: Установка ключа GPG
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        keyring: /etc/apt/trusted.gpg.d/hashicorp-archive-keyring.gpg
        state: present

    - name: Подключение репозитория
      ansible.builtin.apt_repository:
        repo: deb https://apt.releases.hashicorp.com/ bookworm main
        state: present
        filename: hashicorp # /etc/apt/sources.list.d/hashicorp.list
        update_cache: true # apt update

    - name: Установка Terraform
      ansible.builtin.apt:
        name: terraform
        state: present
