---
- name: Install HashiCorp Terraform
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install GPG key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        keyring: /etc/apt/trusted.gpg.d/hashicorp-archive-keyring.gpg
        state: present

    - name: Register HashiCorp APT repository
      ansible.builtin.apt_repository:
        repo: deb https://apt.releases.hashicorp.com/ bookworm main
        state: present
        filename: hashicorp # /etc/apt/sources.list.d/hashicorp.list
        update_cache: true # apt update

    - name: Install Terraform package
      ansible.builtin.apt:
        name: terraform
        state: present
