---
- name: Register Official HashiCorp APT repository
  hosts: all
  become: true

  tasks:
    - name: Register HashiCorp APT repository
      ansible.builtin.deb822_repository:
        name: hashicorp
        types: deb
        uris: https://apt.releases.hashicorp.com/
        suites: "{{ ansible_distribution_release }}"
        components: main
        signed_by: https://apt.releases.hashicorp.com/gpg
        state: present
