---
# На основе статьи Debian Wiki: https://wiki.debian.org/ru/KVM
- name: Install QEMU-KVM
  hosts: all
  become: true

  tasks:
    - name: Install QEMU-KVM packages
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - qemu-kvm
          - libvirt-clients
          - libvirt-daemon-system
          - libvirt-dev  # Для сборки нативного GEM'а Ruby
          - virt-manager
      when:
        - ansible_facts['distribution'] == "Debian"- 
