---
#################################
# Система мониторинга syslog-ng #
#################################

- name: Install sysglog-ng
  hosts: all
  become: true

  tasks:
    - name: Register syslog-ng APT repository
      ansible.builtin.deb822_repository:
        name: syslog-ng
        types: deb
        uris: https://ose-repo.syslog-ng.com/apt/
        suites: stable
        components: "debian-{{ ansible_distribution_release }}"
        signed_by: https://ose-repo.syslog-ng.com/apt/syslog-ng-ose-pub.asc
        state: present

    - name: Install syslog-ng package
      ansible.builtin.apt:
        name: syslog-ng
        state: present
        update_cache: true
