---
- name: Install HashiCorp Terraform from the mirror
  hosts: all
  become: true
  vars:
    version: 1.8.5

  tasks:
    - name: Download ZIP with Terraform DEB
      ansible.builtin.unarchive:
        dest: /tmp
        src: >-
          https://hashicorp-releases.yandexcloud.net/terraform/
          {{ version }}
          /terraform_{{ version }}_linux_{{ ansible_architecture }}.zip

    - name: Install Terraform DEB package
      ansible.builtin.apt:
        deb: "/tmp/terraform_{{ version }}_linux_{{ ansible_architecture }}.deb"
        name: terraform
        state: present
        update_cache: true
