---
namespace: dunaevskii
name: debian
version: 0.0.1
readme: README.md
authors:
  - Maxim Dunaevskii (dunmaksim@yandex.ru)
description: Ansible Collection for faster configuration Debian Linux
license_file: COPYING
tags:
  - linux
  - debian
dependencies:
repository: https://github.com/dunmaksim/ansible-debian-config
documentation:
homepage: https://dunaevsky-ms.ru/
issues: https://github.com/dunmaksim/ansible-debian-config
