---
- name: Register Yandex Disk APT repository
  ansible.builtin.deb822_repository:
    name: yandex-disk
    types: deb
    uris: https://repo.yandex.ru/yandex-disk/deb
    suites: stable
    components: main
    signed_by: https://repo.yandex.ru/yandex-disk/YANDEX-DISK-KEY.GPG
    state: present

- name: Install Yandex Disk package
  ansible.builtin.apt:
    name: yandex-disk
    state: present
    update_cache: true
