---
- name: Install Terraform DEB package from Yandex Cloud mirror
  ansible.builtin.apt:
    deb: >-
      https://hashicorp-releases.yandexcloud.net/vagrant/
      {{ vagrant_version }}/vagrant_{{ vagrant_version }}-1_{{ ansible_architecture }}.deb
    state: present
  when: not vagrant_use_official_repo | bool

- name: Register HashiCorp official APT repository
  ansible.builtin.deb822_repository:
    name: hashicorp
    types: deb
    uris: https://apt.releases.hashicorp.com
    suites: "{{ ansible_distribution_release }}"
    components: main
    signed_by: https://apt.releases.hashicorp.com/gpg
    state: present
  when: vagrant_use_official_repo | bool

- name: Install Vagrant from HashiCorp official APT repository
  ansible.builtin.apt:
    pkg: vagrant
    state: present
    update_cache: true
  when: vagrant_use_official_repo | bool
