# -*- mode: ruby -*-
# frozen_string_literal: true

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
  end
end
