---
- name: Register Microsoft APT repository
  ansible.builtin.deb822_repository:
    name: vscode
    types: deb
    uris: https://packages.microsoft.com/repos/code
    suites: "stable"
    components: main
    signed_by: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Install required packages
  ansible.builtin.apt:
    pkg: code
    state: present
    update_cache: true
