---
######### Переменные роли dunaevskii.backports ########
backports_curl: false
backports_emacs: false
backports_gthumb: false
backports_mc: false
backports_pipewire: false
backports_systemd: false
