---
- name: Register HashiCorp official APT repository
  ansible.builtin.deb822_repository:
    name: hashicorp
    types: deb
    uris: https://apt.releases.hashicorp.com
    suites: "{{ ansible_distribution_release }}"
    components: main
    signed_by: https://apt.releases.hashicorp.com/gpg
    state: present
