---
- name: Register Yandex Browser APT repository
  ansible.builtin.deb822_repository:
    name: yandex-browser
    types: deb
    uris: https://repo.yandex.ru/yandex-browser/deb
    suites: stable
    components: main
    signed_by: https://repo.yandex.ru/yandex-browser/YANDEX-BROWSER-KEY.GPG
    state: present

- name: Install Yandex Browser package
  ansible.builtin.apt:
    name: yandex-browser
    state: present
    update_cache: true
