---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: debian-bookworm64
    box: debian/bookworm64
    memory: 8192
    cpus: 4
    interfaces:
      - network_name: private_network
        ip: 192.168.56.222
provisioner:
  name: ansible
  inventory:
    host_vars:
      debian:
        ansible_become: true
        ansible_user: vagrant
        ansible_password: vagrant
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    - dependency
    - lint
