---
- name: Register Oracle VirtualBox APT repository
  ansible.builtin.deb822_repository:
    name: virtualbox
    types: deb
    uris: https://download.virtualbox.org/virtualbox/debian
    suites: "{{ ansible_distribution_release }}"
    components: contrib
    signed_by: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: Install VirtualBox packages
  ansible.builtin.apt:
    state: present
    pkg:
      - dkms
      - build-essential
      - "linux-headers-{{ ansible_kernel }}"
      - make
      - virtualbox-7.0
    update_cache: true
