---
# https://backports.debian.org/
- name: Connect Debian Bookworm Backports repository
  hosts: all
  become: true

  tasks:
    - name: Register Debian Bookworm Backports repository
      ansible.builtin.deb822_repository:
        name: debian-backports
        types: deb
        uris: https://deb.debian.org/debian
        suites: bookworm-backports
        components:
          - main
          - non-free
          - contrib
        state: present
