---
# https://backports.debian.org/
# Подключение репозитория Debian Bookworm Backports и настройка приоритетов файлов
- name: Connect Debian Bookworm Backports repository
  hosts: all
  become: true

  tasks:
    - name: Register Debian Bookworm Backports repository
      ansible.builtin.deb822_repository:
        name: debian-backports
        types: deb
        uris: https://deb.debian.org/debian
        suites: bookworm-backports
        components:
          - main
          - non-free
          - contrib
        state: present
      when:
        - ansible_facts['distribution'] == "Debian"
        - ansible_facts['ansible_distribution_release'] == "bookworm"

    - name: Create priorities file
      ansible.builtin.file:
        path: /etc/apt/preferences.d/backports
        owner: roor
        group: root
        state: file
        mode: '0644'
      when:
        - ansible_facts['distribution'] == "Debian"
        - ansible_facts['ansible_distribution_release'] == "bookworm"

    - name: Fill backports config file
      ansible.builtin.blockinfile:
        path: /etc/apt/preferences.d/backports
        block: |
          # gThumb
          Package: gthumb gthumb-data
          Pin: release n=bookworm-backports
          Pin-Priority: 600

          # Pipewire
          Package: pipewire pipewire-bin libpipewire
          Pin: release n=bookworm-backports
          Pin-Priority: 600

          # Midnight Commander
          Package: mc mc-data
          Pin: release n=bookworm-backports
          Pin-Priority: 600

          # GNU Emacs
          Package: emacs-gtk emacs-nox emacs emacs-bin-common emacs-common emacs-el
          Pin: release n=bookworm-backports
          Pin-Priority: 600

          # cURL
          Package: curl libcurl3-gnutls libcurl4
          Pin: release n=bookworm-backports
          Pin-Priority: 600
      when:
        - ansible_facts['distribution'] == "Debian"
        - ansible_facts['ansible_distribution_release'] == "bookworm"

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true
      when:
        - ansible_facts['distribution'] == "Debian"
        - ansible_facts['ansible_distribution_release'] == "bookworm"
