---
# https://www.deb-multimedia.org/
- name: Connect Debian Multimedia repository
  hosts: all
  become: true

  tasks:
    - name: Download and install package with GPG key
      ansible.builtin.apt:
        deb: |
          https://www.deb-multimedia.org/pool/main/d/
          deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb

    - name: Register Debian Multimedia repository
      ansible.builtin.deb822_repository:
        name: debian-multimedia
        types: deb
        uris: https://www.deb-multimedia.org
        suites: "{{ ansible_distribution_release }}"
        components:
          - main
          - non-free
        state: present
