---
- name: Install Docker
  hosts: all
  become: true

  tasks:
    - name: Remove Docker packages installed from Debian repositories
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
        purge: true
      with_items:
        - containerd
        - docker
        - docker-engine
        - docker.io
        - runc
      when:
        - ansible_facts['distribution'] == "Debian"


    - name: Register Docker APT repository
      ansible.builtin.deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux
        suites: "debian {{ ansible_distribution_release }}"
        components: stable
        signed_by: https://download.docker.com/linux/debian/gpg
        state: present
      when:
        - ansible_facts['distribution'] == "Debian"

    - name: Install Docker packages
      ansible.builtin.apt:
        pkg:
          containerd.io
          docker-buildx-plugin
          docker-ce
          docker-ce-cli
          docker-compose-plugin
        update_cache: true
      when:
        - ansible_facts['distribution'] == "Debian"
