---
- name: Install GNU Eemacs with extensions
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Search and uninstall Emacs Nox
      ansible.builtin.apt:
        name: emacs-nox
        state: absent
        purge: true

    - name: Install GNU Emacs
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - emacs
