---
- name: Install Mozilla Firefox from Mozilla APT repository
  hosts: all
  become: true

  tasks:
    - name: Register Mozilla APT repository
      ansible.builtin.deb822_repository:
        name: mozilla
        types: deb
        uris: https://packages.mozilla.org/apt
        suites: mozilla
        components: main
        signed_by: https://packages.mozilla.org/apt/repo-signing-key.gpg
        state: present
      when:
        - ansible_facts['distribution'] == "Debian"

    - name: Create Mozilla repository priority file
      ansible.builtin.file:
        path: /etc/apt/preferences.d/mozilla
        owner: root
        group: root
        state: file
        mode: '0644'
      when:
        - ansible_facts['distribution'] == "Debian"

    - name: Fill Mozilla repository priority file
      ansible.builtin.blockinfile:
        path: /etc/apt/preferences.d/mozilla
        block: |
          Package: *
          Pin: origin packages.mozilla.org
          Pin-Priority: 1000
      when:
        - ansible_facts['distribution'] == "Debian"

    - name: Uninstall Mozilla Firefox ESR
      ansible.builtin.apt:
        name: firefox-esr
        state: absent
        purge: true
      when:
        - ansible_facts['distribution'] == "Debian"

    - name: Install Mozilla Firefox from Mozilla repository
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - firefox
      when:
        - ansible_facts['distribution'] == "Debian"
