---
- name: Install Mattermost desktop client
  hosts: all
  become: true

  tasks:
    - name: Register Mattermost APT repository
      ansible.builtin.deb822_repository:
        name: mattermost
        types: deb
        uris: https://deb.packages.mattermost.com
        suites: stable
        components: main
        signed_by: https://deb.packages.mattermost.com/pubkey.gpg
        state: present
      when:
        - ansible_facts['distribution'] == "Debian"

    - name: Install Mattermost Desktop package
      ansible.builtin.apt:
        name: mattermost-desktop
        state: present
        update_cache: true
      when:
        - ansible_facts['distribution'] == "Debian"
