---
- name: Install Node.JS 20.x from NodeSource
  hosts: all
  become: true

  tasks:
    - name: Register NodeJS APT repository
      ansible.builtin.deb822_repository:
        name: nodejs
        types: deb
        uris: https://deb.nodesource.com/node_20.x
        suites: nodistro
        components: main
        signed_by: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
        state: present

    - name: Install NodeJS package
      ansible.builtin.apt:
        name: nodejs
        state: present
        update_cache: true
