---
- name: Install Node.JS 20.x
  hosts: all
  become: true

  tasks:
    - name: Install GPG key
      ansible.builtin.apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        keyring: /etc/apt/trusted.gpg.d/nodesource.gpg
        state: present

    - name: Register Node.JS APT repository
      ansible.builtin.apt_repository:
        repo: deb https://deb.nodesource.com/node_20.x nodistro main
        state: present
        filename: nodejs  # /etc/apt/sources.list.d/nodesource.list
        update_cache: true  # apt update

    - name: Install NodeJS package
      ansible.builtin.apt:
        name: nodejs
        state: present
