---
# Установка и настройка Podman
# В версии 3.4.1 и ниже используется драйвер vfs, что приводит к
# перерасходу места на диске
# Драйвер overlayfs решает эту проблему.
- name: Install Podman
  hosts: all
  become: true

  tasks:
    - name: Install Podman package
      ansible.builtin.apt:
        pkg:
          podman
      when:
        - ansible_facts['distribution'] == "Debian"

    - name: Create /etc/container/container.conf file
      ansible.builtin.file:
        path: /etc/containers/containers.conf
        owner: root
        group: root
        mode: '0644'
        state: file

    - name: Fill /etc/container/container.conf file
      ansible.builtin.blockinfile:
        path: /etc/containers/containers.conf
        block: |
          [storage]
          driver = "overlay"

    - name: Restart Podman service
      ansible.builtin.systemd_service:
        name: podman
        state: restarted
