---
- name: Install Ruby on Rails
  hosts: all
  become: true

  tasks:
    - name: Install core Ruby packages
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - ruby
      when:
        - ansible_facts['distribution'] == "Debian"

    - name: Install development files for building native Ruby extensions
      ansible.builtin.apt:
        update_cache: false
        pkg:
          - libedit-dev
          - libffi-dev
          - libssl-dev
          - libyaml-dev
          - ruby-dev
      when:
        - ansible_facts['distribution'] == "Debian"
