---
- name: Install HashiCorp Terraform
  hosts: all
  become: true

  tasks:
    - name: Register HashiCorp APT repository
      ansible.builtin.deb822_repository:
        name: hashicorp
        types: deb
        uris: https://apt.releases.hashicorp.com/
        suites: "{{ ansible_distribution_release }}"
        components: main
        signed_by: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Install Terraform package
      ansible.builtin.apt:
        name: terraform
        state: present
        update_cache: true
