---
- name: Install Oracle VirtualBox
  hosts: all
  become: true

  tasks:
    - name: Register Oracle VirtualBox APT repository
      ansible.builtin.deb822_repository:
        name: virtualbox
        types: deb
        uris: https://download.virtualbox.org/virtualbox/debian
        suites: "{{ ansible_distribution_release }}"
        components: contrib
        signed_by: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present

    - name: Install required packages
      ansible.builtin.apt:
        update_cache: true
        state: present
        pkg:
          - dkms
          - build-essential
          - "linux-headers-{{ ansible_kernel }}"
          - virtualbox-7.0
