---
- name: Install Microsoft Visual Studio Code
  hosts: all
  become: true

  tasks:
    - name: Register Microsoft APT repository
      ansible.builtin.deb822_repository:
        name: vscode
        types: deb
        uris: https://packages.microsoft.com/repos/code
        suites: "stable"
        components: main
        signed_by: https://packages.microsoft.com/keys/microsoft.asc
        state: present
      when:
        - ansible_facts['distribution'] == "Debian"

    - name: Install required packages
      ansible.builtin.apt:
        pkg: code
        state: present
        update_cache: true
      when:
        - ansible_facts['distribution'] == "Debian"
