---
- name: Install Yandex Browser
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install GPG key
      ansible.builtin.apt_key:
        url: https://repo.yandex.ru/yandex-browser/YANDEX-BROWSER-KEY.GPG
        keyring: /etc/apt/trusted.gpg.d/virtualbox-2016.gpg
        state: present

    - name: Register Yandex Browser APT repository
      ansible.builtin.apt_repository:
        repo: deb https://repo.yandex.ru/yandex-browser/deb stable main
        state: present
        filename: yandex-browser # /etc/apt/sources.list.d/yandex-browser.list
        update_cache: true  # apt update

    - name: Install Yandex Browser package
      ansible.builtin.apt:
        name: yandex-browser
        state: present
